name: 'Analyze Image (dive)'
description: |
  Analyze a container image using dive (https://github.com/wagoodman/dive).

  This will output statistics about the layers, size, and wasted space in the image.
inputs:
  image:
    description: 'Image to analyze'
    required: true
  docker-socket:
    description: 'Path to the docker socket'
    required: false
    default: '/var/run/docker.sock'
outputs: {}
runs:
  using: 'composite'
  steps:
    - name: Analyze with Dive
      shell: bash
      run: |
        docker run \
        --rm \
        -v ${{ inputs.docker-socket }}:/var/run/docker.sock \
        -e CI=true \
        wagoodman/dive:latest \
        ${{ inputs.image }}
    - name: Print (uncompressed) total size
      shell: bash
      run: |
        docker inspect -f "{{ .Size }}" ${{ inputs.image }} | awk '{ byte =$1 /1024/1024; print byte " MB" }'
    - name: Print layers
      shell: bash
      run: |
        docker history ${{ inputs.image }}
