name: Engineering Improvement
description: Report problems or suggestions to improve the Radius Dashboard engineering processes and/or pipelines
title: '<TITLE>'
labels: ['maintenance']
body:
  - type: markdown
    attributes:
      value: '## Engineering Improvement'
  - type: textarea
    attributes:
      label: Area for Improvement
      description: What engineering process or tools can be improved? Build? Testing? ...? Be specific.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Observed behavior
      description: What you're experiencing that you believe could be improved.
      placeholder: |
        If applicable, add screenshots to help explain your problem.

        Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Desired behavior
      description: What you'd like to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Fix
      description: Have you found a way to implement or fix the issue?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        What browser (Chrome, Firefox, Edge, etc.) are you using to access the dashboard? For example: Chrome Version 121.0.6167.85 (Official Build) (arm64)

        What rad cli version are you running? You can run `rad version` and past the output here.

        Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Would you like to support us?
      description: Would you like to support us in improving Radius engineering processes and/or pipelines?
      options:
        - label: Yes, I would like to support you
          required: false
