# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
---
name: Dev Container Build

on:
  push:
    branches:
      - main
    paths:
      - ".devcontainer/**"
      - ".github/workflows/devcontainer.yaml"
  pull_request:
    branches:
      - main
    paths:
      - ".devcontainer/**"
      - ".github/workflows/devcontainer.yaml"

permissions: {}

jobs:
  build:
    name: Build Dev Container
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Build Dev Container
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6 # v0.3
        with:
          runCmd: node --version && yarn --version && kubectl version --client && rad version
